#! /bin/sh

# assemble jar file
echo 'assembling fat jar...'
sbt assembly

# determine fat jar location and google cloud storage bucket
jar_path='./target/scala-2.10/ResultRankingService-assembly-1.0.jar'
gs_bucket='gs://dataproc-f5363994-7330-4c34-ae81-9b62640328ae-asia/'

echo '*******************************' && echo

# upload 
echo 'uploading assembled jar file to google cloud storage...'
gsutil cp $jar_path $gs_bucket

echo '*******************************' && echo

sbin/submit