#! /bin/sh

# kill running job
echo 'killing running job...'
sbin/kill

echo '*******************************' && echo

# submit spark job
open 'http://104.155.219.53:8088'
echo 'submiting spark job using recently uploaded jar...'

gs_bucket='gs://dataproc-f5363994-7330-4c34-ae81-9b62640328ae-asia'

gcloud dataproc jobs submit spark \
 --cluster recommendation-cluster \
 --jar $gs_bucket/ResultRankingService-assembly-1.0.jar
