#! /bin/sh

curl -XPOST -H "Content-type: application/json" -d '{
    "path": "gs://dataproc-e05f76e4-9b48-40cb-a488-8269e8a72d51-asia/wongnai-logfile/most_10000_active_users_log.csv"
}' '104.155.200.162:8080/personalize/train'